### PR TITLE
Add CRP6-III PDS channel map

### PR DESCRIPTION
**Pull request by YoannKermaidic**
PR that goes along with the new CRP+PDS reconstruction fhicl file
https://github.com/DUNE/dunesw/pull/127

### CODE REVIEW

**Comment by tomjunk** [comment]
CRP6 TPC+PDS reconstruction dunesw PR #127 has a lingering question -- does something need to be fixed before merging?

**Comment by YoannKermaidic** [comment]
Hi @tomjunk ,
I'm working on finalizing this PR such that it can be merged

**Comment by YoannKermaidic** [comment]
Ready for merge =)

**Comment by aolivier23** [comment]
trigger build with dune/duneprototypes#50

**Review by aolivier23 — APPROVED** [review]
New .txt files shouldn't break anything.  I'll confirm that when I run CI for the release candidate.

**Pull request merged**
